server:
  port: 9020
  tomcat:
    uri-encoding: utf-8
spring:
  druid:
    #数据库访问配置，使用druid数据源
    db-type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3308/db_vote?userUnicode=true&characterEncoding=UTF-8&useJDBCComploantTimezoneShift=true&useLegacyDatetimeCode
    =false&serverTimezonr=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    #连接池配置
    initial-size: 5
    min-idle: 5
    max-acitve: 20
    #连接等待超时时间
    max-wait: 3000
    #配置检测可以关闭的空闲连接间隔时间
    time-between-eviction-runs-mills: 60000
    #配置在连接池中最小生存时间
    min-evictable-idle-time-mills: 300000
    validation-query: select '1' from dual
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    #打开PSCache，并且指定每个连接上PSCache的大小
    pool-prepared-statements: true
    max-open-prepared-statements: 20
    max-pool-prepared-statement-per-connection-size: 20
    #配置监控统计拦截的filters，去掉后监控界面sql无法统计，wall用于防火墙
    filters: stat
    #spring监控AOP切入点，如x.y.x.service.*配置对个英文句号分隔
    aop-patterns: com.sxz.*.service.*
    #WebStatFilter配置
    web-stat-filter:
      enable: true
      #添加过滤规则
      url-pattern: /*
      #忽略过滤的格式
      exclusions: '*.js,*.gif,*.jpg,*,png,*.css,*.ico,/druid/*,/actuator/*'
      #statViewServlet配置
      stat-view-servlet:
        enable: true
        #访问路径为druid时，跳转到statViewServlet
        url-pattern: /druid/*
        #是否能够重置数据
        reset-enable: false
        #需要账号密码才能访问控制台
        login-username: druid
        login-password: druid123
      #配置StatFilter
      filter:
        stat:
          log-slow-sql:true
  redis:
    #Redis数据库索引（默认为0）
    database: 0
    #Redis服务器地址
    host: 127.0.0.1
    #Redis服务器连接端口
    port: 6379
    #Redis密码
    password:
    jedis:
      pool:
        #连接池中最小空闲连接
        min-idle: 8
        #连接池中最大空闲连接
        max-idle: 500
        #连接池中最大连接数
        max-active: 2000
        #连接池中最大阻塞等待时间
        max-wait: 10000
      timeout: 0
  thymeleaf:
    cache: false
  aop:
    proxy-target-class: true
  cache:
    type:
      redis
mybatis:
  #mybati-alias扫描路径
  type-aliases-package: com.xsz.system.domain,com.xsz.job.domain
  #mapper。xml实现扫描路径
  mapper-locations: classpath:mapper/*/*.xml
  configuration:
    jdbc-type-for-null: null
  #多个模块的多个包配置可以使用英文句号分隔
  type-handlers-package: com.xsz.common.util.enuls

#文件上传路径
file.upload.path: F://images//
file.upload.path.relative: /images/
imagePath: file:/F:/images/
mapper:
  mappers: com.sxz.common.config.MyMapper
  not-empty: false
  identity: MYSQL
pagehelper:
  dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
#XSZ配置
xsz:
  #是否在控制台打印sql语句
  showsql: true
  timeFormat: yyyy-MM-dd HH:mm:ss
  #是否开启AOP
  openAopLog: true
  shiro:
    #shiro Redis缓存时长，默认1800s
    expireIn: 1800
    #session 超时时间，默认1800000ms
    sessionTimeout: 1800000
    #rememberMe cookie有效市场，默认86400s，即一天
    cookieTimeout: 86400
    #免认证的路径配置，如静态资源，druid监控页面，注册页面，验证码请求等
    annoUrl: /css/**,/js/**,/fonts/**,/img/**,/druid/**,/user/regist,/gifCode,/actuator/**,/test/**
    #登录url
    loginUrl: /login
    #登录成功后跳转的url
    successUrl: /index
    #登出url
    logoutUrl: /logout
    #未经授权跳转
    unauthorizedUrl :/403
  #验证啊
  validateCode:
    width: 146
    height: 33
    length: 4
swagger:
  enable: true